# Starter pipeline
# Pull from Repo
# Import Project into Docekr SOAtest CLI container and Run
# Azure YAML docs:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# Set Up Project
steps:
- script: |
    echo "Starting Pipeline Execution."

    echo $"
    apiVersion: '2019-12-01'
    location: eastus
    name: file-share-demo
    properties:
    containers:
    - name: hellofiles
    properties:
    environmentVariables: []
    image: mcr.microsoft.com/azuredocs/aci-hellofiles
    ports:
    - port: 80
    resources:
    requests:
    cpu: 1.0
    memoryInGB: 1.5
    volumeMounts:
    - mountPath: /aci/logs/
    name: parasoftfiles
    osType: Linux
    restartPolicy: Always
    ipAddress:
    type: Public
    ports:
    - port: 80
    dnsNameLabel: aci-demo
    volumes:
    - name: parasoftfiles
    azureFile:
    sharename: parasoftfiles
    storageAccountName: adoproject
    storageAccountKey: liZ+KvFZBAgxHMDkb8z7MdV9NPFfma0M0EjtgFLG2Yk2InBwwkJXjGfpe5r6Ljexn8XKOnif1rrg+AStdt6c/w==
    tags: {}
    type: Microsoft.ContainerInstance/containerGroups" >>temp/deploy-aci.yml

    az container create --resource-group ADOProject_group --file deploy-aci.yaml
